-- Generado por scripts/sync-productos.js
-- Pegalo en Supabase -> SQL Editor -> Run
insert into productos_meta (alegra_id, nombre_cache, categoria, unidad)
values
  ('18', 'Banrol', 'otros', 'Por unidad'),
  ('4', 'Bayetilla', 'otros', 'Por metro'),
  ('39', 'Bayetilla en poliester', 'otros', 'Por metro'),
  ('41', 'Bolsillo espiga', 'otros', 'Por metro'),
  ('36', 'Borraflojo', 'otros', 'Por unidad'),
  ('19', 'caja tiza', 'tizas', 'Por caja'),
  ('22', 'caja tiza blanca, 50 unidades', 'tizas', 'Por caja'),
  ('21', 'caja tiza color 50 unidades', 'tizas', 'Por caja'),
  ('38', 'Caja tiza color pequeña', 'tizas', 'Por caja'),
  ('27', 'cremallera cobre 20 cmts', 'cierres', 'Por unidad'),
  ('43', 'Dacrón', 'otros', 'Por metro'),
  ('12', 'Entretela', 'entretelas', 'Por metro'),
  ('1', 'entretela doble punto', 'entretelas', 'Por metro'),
  ('15', 'entretela doble punto 90gr', 'entretelas', 'Por metro'),
  ('35', 'Entretela galleta', 'entretelas', 'Por metro'),
  ('33', 'Entretela granulada', 'entretelas', 'Por metro'),
  ('7', 'entretela para cuello de camisa', 'entretelas', 'Por metro'),
  ('6', 'entretela poliestar', 'entretelas', 'Por metro'),
  ('14', 'Forro arabesco', 'forros', 'Por metro'),
  ('9', 'Forro brioni', 'forros', 'Por metro'),
  ('42', 'Forro brioni 70 gr', 'forros', 'Por metro'),
  ('13', 'Forro estampado', 'forros', 'Por metro'),
  ('32', 'Forro estampado grueso', 'forros', 'Por metro'),
  ('40', 'Forro Poliviscosa', 'forros', 'Por metro'),
  ('23', 'Guata', 'guatas', 'Por metro'),
  ('37', 'Guata fusionable', 'guatas', 'Por metro'),
  ('5', 'Hombrera', 'hombreras', 'Por par'),
  ('17', 'Hombrera algodón 2 capas', 'hombreras', 'Por par'),
  ('2', 'Hombrera en algodón', 'hombreras', 'Por par'),
  ('16', 'Hombrera espuma blanca', 'hombreras', 'Por par'),
  ('3', 'Hombrera negra', 'hombreras', 'Por par'),
  ('8', 'Interlón', 'otros', 'Por metro'),
  ('24', 'Interlón telfor', 'otros', 'Por metro'),
  ('20', 'Liencillo', 'otros', 'Por metro'),
  ('26', 'Lona calima', 'otros', 'Por metro'),
  ('10', 'portavestido', 'otros', 'Por metro'),
  ('25', 'Pretina', 'otros', 'Por metro'),
  ('11', 'Sido', 'otros', 'Por metro'),
  ('34', 'Valencina', 'otros', 'Por metro')
on conflict (alegra_id) do update
  set nombre_cache = excluded.nombre_cache;
